// SPDX-License-Identifier: GPL-3.0-only
// Généré par tooling/corpus-tests/harvest/core_fixtures.ts : verdicts du vrai Jinja (2.11.3 pour
// Klipper, 3.1.6 pour Kalico) sur les cas limites. Ne pas modifier à la main.

export type JinjaVerdict = null | { readonly line: number; readonly message: string } | { readonly python: string };

export const JINJA_CASES: readonly {
  readonly name: string;
  readonly template: string;
  readonly klipper: JinjaVerdict;
  readonly kalico: JinjaVerdict;
}[] = [
  {"name":"macro typique","template":"\n{% set bed = params.BED_TEMP|default(60)|float %}\n{% if 'xyz' not in printer.toolhead.homed_axes %}\nG28\n{% endif %}\nM190 S{bed}\nG1 X{printer.toolhead.axis_maximum.x / 2} F3000\n{action_respond_info(\"Prêt\")}","klipper":null,"kalico":null},
  {"name":"for avec else, filtre et test","template":"{% for s in printer.configfile.settings if s.startswith('stepper') %}\nM118 {s|upper}\n{% else %}\nM118 aucun\n{% endfor %}\n{% if x is divisibleby 3 and y is not none %}ok{% endif %}","klipper":null,"kalico":null},
  {"name":"set bloc et namespace","template":"{% set ns = namespace(n=0) %}{% set ns.n = ns.n + 1 %}{% set txt %}bloc{% endset %}{txt}","klipper":null,"kalico":null},
  {"name":"macro et call","template":"{% macro m(a, b=2) %}{a}{b}{% endmacro %}{% call m(1) %}c{% endcall %}{m(1, b=3)}","klipper":null,"kalico":null},
  {"name":"dictionnaire et tranches","template":"{ {'a': 1, 'b': [1, 2]}['b'][0] }{ 'abc'[1:] }{ (1, 2)[::-1] }{ [1,2,3]|join(',') }","klipper":null,"kalico":null},
  {"name":"contrôle des blancs","template":"{%- if x -%}\n  G28\n{%- endif -%}\n{- x -}","klipper":null,"kalico":null},
  {"name":"raw","template":"{% raw %}{% if pas du jinja { %}{% endraw %}","klipper":null,"kalico":null},
  {"name":"accolade fermante seule dans le texte","template":"M117 fin }","klipper":null,"kalico":null},
  {"name":"concaténation, puissance, conditionnelle","template":"{ 'a' ~ 1 ~ \"b\" }{ 2 ** 3 // 2 % 3 }{ 'oui' if x else 'non' }{ -x + +y }{ a < b <= c != d }","klipper":null,"kalico":null},
  {"name":"appels avec *args et **kwargs","template":"{ f(*a, **b) }{ f(1, x=2, *a) }","klipper":null,"kalico":null},
  {"name":"chaînes accolées","template":"{ 'a' 'b' }","klipper":null,"kalico":null},
  {"name":"commentaire Jinja","template":"{# commentaire #}G28","klipper":null,"kalico":null},
  {"name":"nombre 1.5e3 et _","template":"{ 1.5e3 }{ 1_000 }","klipper":null,"kalico":null},
  {"name":"with, filter, autoescape","template":"{% with a = 1 %}{a}{% endwith %}{% filter upper %}x{% endfilter %}{% autoescape false %}y{% endautoescape %}","klipper":null,"kalico":null},
  {"name":"if non fermé","template":"\n{% if printer.extruder.temperature < 200 %}\nM109 S200\nG28","klipper":{"line":2,"message":"Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."},"kalico":{"line":2,"message":"Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."}},
  {"name":"for non fermé","template":"{% for i in range(3) %}\nG1 Z1","klipper":{"line":1,"message":"Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'."},"kalico":{"line":1,"message":"Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'."}},
  {"name":"set bloc non fermé","template":"{% set x %}bloc","klipper":{"line":1,"message":"Unexpected end of template. Jinja was looking for the following tags: 'endset'. The innermost block that needs to be closed is 'set'."},"kalico":{"line":1,"message":"Unexpected end of template. Jinja was looking for the following tags: 'endset'. The innermost block that needs to be closed is 'set'."}},
  {"name":"endif orphelin","template":"G28\n{% endif %}","klipper":{"line":2,"message":"Encountered unknown tag 'endif'."},"kalico":{"line":2,"message":"Encountered unknown tag 'endif'."}},
  {"name":"else hors bloc","template":"{% else %}","klipper":{"line":1,"message":"Encountered unknown tag 'else'."},"kalico":{"line":1,"message":"Encountered unknown tag 'else'."}},
  {"name":"endfor au lieu de endif","template":"{% if x %}\nG28\n{% endfor %}","klipper":{"line":3,"message":"Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."},"kalico":{"line":3,"message":"Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."}},
  {"name":"balise inconnue (do)","template":"{% do x.append(1) %}","klipper":{"line":1,"message":"Encountered unknown tag 'do'."},"kalico":null},
  {"name":"break sans extension","template":"{% for i in x %}{% break %}{% endfor %}","klipper":{"line":1,"message":"Encountered unknown tag 'break'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'."},"kalico":null},
  {"name":"affectation dans un if","template":"{% if x = 1 %}G28{% endif %}","klipper":{"line":1,"message":"expected token 'end of statement block', got '='"},"kalico":{"line":1,"message":"expected token 'end of statement block', got '='"}},
  {"name":"set avec ==","template":"{% set x == 1 %}","klipper":{"line":1,"message":"expected token 'end of statement block', got '=='"},"kalico":{"line":1,"message":"expected token 'end of statement block', got '=='"}},
  {"name":"filtre vide","template":"{ params.X | }","klipper":{"line":1,"message":"expected token 'name', got 'end of print statement'"},"kalico":{"line":1,"message":"expected token 'name', got 'end of print statement'"}},
  {"name":"deux noms accolés","template":"{ x y }","klipper":{"line":1,"message":"expected token 'end of print statement', got 'y'"},"kalico":{"line":1,"message":"expected token 'end of print statement', got 'y'"}},
  {"name":"for sans in","template":"{% for x %}{% endfor %}","klipper":{"line":1,"message":"expected token 'in', got 'end of statement block'"},"kalico":{"line":1,"message":"expected token 'in', got 'end of statement block'"}},
  {"name":"for in vide","template":"{% for x in %}{% endfor %}","klipper":{"line":1,"message":"Expected an expression, got 'end of statement block'"},"kalico":{"line":1,"message":"Expected an expression, got 'end of statement block'"}},
  {"name":"if vide","template":"{% if %}{% endif %}","klipper":{"line":1,"message":"Expected an expression, got 'end of statement block'"},"kalico":{"line":1,"message":"Expected an expression, got 'end of statement block'"}},
  {"name":"variable vide","template":"M117 { }","klipper":{"line":1,"message":"Expected an expression, got 'end of print statement'"},"kalico":{"line":1,"message":"Expected an expression, got 'end of print statement'"}},
  {"name":"bloc vide","template":"{% %}","klipper":{"line":1,"message":"tag name expected"},"kalico":{"line":1,"message":"tag name expected"}},
  {"name":"accolade ouvrante seule","template":"M117 {","klipper":{"line":1,"message":"unexpected 'end of template'"},"kalico":{"line":1,"message":"unexpected 'end of template'"}},
  {"name":"expression non fermée","template":"M117 { x\nG28","klipper":{"line":2,"message":"expected token 'end of print statement', got 'G28'"},"kalico":{"line":2,"message":"expected token 'end of print statement', got 'G28'"}},
  {"name":"parenthèse non fermée","template":"{ (1 + 2 }","klipper":{"line":1,"message":"unexpected '}', expected ')'"},"kalico":{"line":1,"message":"unexpected '}', expected ')'"}},
  {"name":"crochet non fermé","template":"{ [1, 2 }","klipper":{"line":1,"message":"unexpected '}', expected ']'"},"kalico":{"line":1,"message":"unexpected '}', expected ']'"}},
  {"name":"parenthèse en trop","template":"{ 1 + 2) }","klipper":{"line":1,"message":"unexpected ')'"},"kalico":{"line":1,"message":"unexpected ')'"}},
  {"name":"caractère inattendu","template":"{ x @ y }","klipper":{"line":1,"message":"unexpected char '@' at 4"},"kalico":{"line":1,"message":"unexpected char '@' at 4"}},
  {"name":"opérateur final","template":"{ 1 + }","klipper":{"line":1,"message":"unexpected 'end of print statement'"},"kalico":{"line":1,"message":"unexpected 'end of print statement'"}},
  {"name":"attribut vide","template":"{ a. }","klipper":{"line":1,"message":"expected name or number"},"kalico":{"line":1,"message":"expected name or number"}},
  {"name":"indice vide","template":"{ a[] }","klipper":null,"kalico":null},
  {"name":"chaîne non fermée","template":"{ 'abc }","klipper":{"line":1,"message":"unexpected char \"'\" at 2"},"kalico":{"line":1,"message":"unexpected char \"'\" at 2"}},
  {"name":"hexadécimal","template":"{ 0x10 }","klipper":{"line":1,"message":"expected token 'end of print statement', got 'x10'"},"kalico":null},
  {"name":"filtre inconnu","template":"\n{% set s = params.S|floatt %}","klipper":{"line":2,"message":"no filter named 'floatt'"},"kalico":{"line":2,"message":"No filter named 'floatt'."}},
  {"name":"test inconnu","template":"{% if x is nombre %}{% endif %}","klipper":{"line":1,"message":"no test named 'nombre'"},"kalico":null},
  {"name":"filtre inconnu dans un bloc non exécuté","template":"{% if false %}{ x|inconnu }{% endif %}","klipper":{"line":1,"message":"no filter named 'inconnu'"},"kalico":null},
  {"name":"endmacro orphelin","template":"{% endmacro %}","klipper":{"line":1,"message":"Encountered unknown tag 'endmacro'."},"kalico":{"line":1,"message":"Encountered unknown tag 'endmacro'."}},
  {"name":"raw non fermé","template":"{% raw %}abc","klipper":{"line":1,"message":"Missing end of raw directive"},"kalico":{"line":1,"message":"Missing end of raw directive"}},
  {"name":"commentaire non fermé","template":"{# abc","klipper":{"line":1,"message":"Missing end of comment tag"},"kalico":{"line":1,"message":"Missing end of comment tag"}},
  {"name":"elif après else","template":"{% if a %}{% else %}{% elif b %}{% endif %}","klipper":{"line":1,"message":"Encountered unknown tag 'elif'. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'."},"kalico":{"line":1,"message":"Encountered unknown tag 'elif'. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'."}},
  {"name":"virgule finale en appel","template":"{ f(1,) }","klipper":null,"kalico":null},
  {"name":"mot-clé comme nom","template":"{ if }","klipper":null,"kalico":null},
  {"name":"is sans test","template":"{ x is }","klipper":{"line":1,"message":"expected token 'name', got 'end of print statement'"},"kalico":{"line":1,"message":"expected token 'name', got 'end of print statement'"}},
  {"name":"doubles accolades (Jinja standard)","template":"M117 {{ printer.toolhead.position.z }}","klipper":{"line":1,"message":"expected token ':', got '}'"},"kalico":{"line":1,"message":"expected token ':', got '}'"}},
  {"name":"doubles accolades autour d'un dictionnaire valide","template":"{ {'a': 1}.a }","klipper":null,"kalico":null},
  {"name":"test enchaîné","template":"{ x is defined is true }","klipper":{"line":1,"message":"You cannot chain multiple tests with is"},"kalico":{"line":1,"message":"You cannot chain multiple tests with is"}},
  {"name":"arguments après **kwargs","template":"{ f(**a, b) }","klipper":{"line":1,"message":"invalid syntax for function call expression"},"kalico":{"line":1,"message":"invalid syntax for function call expression"}},
  {"name":"for avec recursive et test","template":"{% for x in y if x recursive %}{loop.depth}{% endfor %}","klipper":null,"kalico":null},
  {"name":"import et from","template":"{% import 'a' as b %}{% from 'a' import c as d, e with context %}{% include 'x' ignore missing %}","klipper":null,"kalico":null},
  {"name":"print","template":"{% print 1, 2 %}","klipper":null,"kalico":null},
  {"name":"macro sans parenthèses","template":"{% macro m %}{% endmacro %}","klipper":{"line":1,"message":"expected token '(', got 'end of statement block'"},"kalico":{"line":1,"message":"expected token '(', got 'end of statement block'"}},
  {"name":"ordre : erreur de syntaxe avant filtre inconnu","template":"{ a }\n{ b|inconnu }\n{% if c %}","klipper":{"line":3,"message":"Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."},"kalico":{"line":3,"message":"Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."}},
  {"name":"ordre : balise inconnue avant caractère inattendu plus loin","template":"{% endif %} { x @ y }","klipper":{"line":1,"message":"Encountered unknown tag 'endif'."},"kalico":{"line":1,"message":"Encountered unknown tag 'endif'."}},
  {"name":"ordre : caractère inattendu avant balise orpheline plus loin","template":"{ x @ y } {% endif %}","klipper":{"line":1,"message":"unexpected char '@' at 4"},"kalico":{"line":1,"message":"unexpected char '@' at 4"}},
  {"name":"ordre : filtres enchaînés, le dernier d'abord","template":"{ x|inconnu1|inconnu2 }","klipper":{"line":1,"message":"no filter named 'inconnu2'"},"kalico":{"line":1,"message":"No filter named 'inconnu2'."}},
  {"name":"ordre : test du for avant l'itérable","template":"{% for x in y|inconnu1 if x|inconnu2 %}{% endfor %}","klipper":{"line":1,"message":"no filter named 'inconnu2'"},"kalico":{"line":1,"message":"No filter named 'inconnu2'."}},
  {"name":"ordre : arguments nommés avant *args","template":"{ f(*a|inconnu1, b=c|inconnu2) }","klipper":{"line":1,"message":"no filter named 'inconnu2'"},"kalico":{"line":1,"message":"No filter named 'inconnu2'."}},
  {"name":"ordre : argument nommé mot-clé Python","template":"{ f(*a|inconnu1, if=c|inconnu2) }","klipper":{"line":1,"message":"no filter named 'inconnu1'"},"kalico":{"line":1,"message":"No filter named 'inconnu1'."}},
  {"name":"ordre : corps du set avant son filtre","template":"{% set x | inconnu1 %}{ y|inconnu2 }{% endset %}","klipper":{"line":1,"message":"no filter named 'inconnu2'"},"kalico":{"line":1,"message":"No filter named 'inconnu2'."}},
  {"name":"ordre : blocs après le reste","template":"{% block b %}{ x|inconnu1 }{% endblock %}{ y|inconnu2 }","klipper":{"line":1,"message":"no filter named 'inconnu2'"},"kalico":{"line":1,"message":"No filter named 'inconnu2'."}},
  {"name":"filtre inconnu dans un if","template":"{% if x %}\n{ y|inconnu }\n{% endif %}","klipper":{"line":2,"message":"no filter named 'inconnu'"},"kalico":null},
  {"name":"filtre inconnu dans une condition de if","template":"{% if x|inconnu %}{% endif %}","klipper":{"line":1,"message":"no filter named 'inconnu'"},"kalico":null},
  {"name":"filtre inconnu dans une expression conditionnelle","template":"{ y|inconnu if x else 0 }","klipper":{"line":1,"message":"no filter named 'inconnu'"},"kalico":null},
  {"name":"filtre inconnu dans un for dans un if","template":"{% if x %}{% for i in y %}{ i|inconnu }{% endfor %}{% endif %}","klipper":{"line":1,"message":"no filter named 'inconnu'"},"kalico":{"line":1,"message":"No filter named 'inconnu'."}},
  {"name":"test inconnu dans un if","template":"{% if x is inconnu %}{% endif %}","klipper":{"line":1,"message":"no test named 'inconnu'"},"kalico":null},
  {"name":"filtre inconnu dans un bloc filter","template":"{% filter inconnu %}x{% endfilter %}","klipper":{"line":1,"message":"no filter named 'inconnu'"},"kalico":{"line":1,"message":"No filter named 'inconnu'."}},
  {"name":"filtre inconnu dans un with","template":"{% with a = x|inconnu %}{a}{% endwith %}","klipper":{"line":1,"message":"no filter named 'inconnu'"},"kalico":{"line":1,"message":"No filter named 'inconnu'."}},
  {"name":"filtre inconnu sur plusieurs lignes","template":"{ x\n  |inconnu }","klipper":{"line":2,"message":"no filter named 'inconnu'"},"kalico":{"line":2,"message":"No filter named 'inconnu'."}},
  {"name":"test inconnu sur plusieurs lignes","template":"{% set a = x\n is inconnu %}","klipper":{"line":2,"message":"no test named 'inconnu'"},"kalico":{"line":2,"message":"No test named 'inconnu'."}},
  {"name":"repliement : false and","template":"{ false and x|inconnu }","klipper":null,"kalico":null},
  {"name":"repliement : true or","template":"{% set a = true or x|inconnu %}","klipper":null,"kalico":null},
  {"name":"repliement : conditionnelle constante","template":"{% set a = 1 if true else x|inconnu %}","klipper":null,"kalico":null},
  {"name":"repliement : not","template":"{ not 0 or x|inconnu }","klipper":null,"kalico":null},
  {"name":"repliement impossible","template":"{ x and y|inconnu }","klipper":{"line":1,"message":"no filter named 'inconnu'"},"kalico":{"line":1,"message":"No filter named 'inconnu'."}},
  {"name":"repliement sous autoescape variable (sortie)","template":"{% autoescape x %}{ false and y|inconnu }{% endautoescape %}","klipper":null,"kalico":null},
  {"name":"repliement sous autoescape variable (set)","template":"{% autoescape x %}{% set z = false and y|inconnu %}{% endautoescape %}","klipper":{"line":1,"message":"no filter named 'inconnu'"},"kalico":{"line":1,"message":"No filter named 'inconnu'."}},
  {"name":"extends dans un if","template":"{% if x %}{% extends 'a' %}{% endif %}","klipper":null,"kalico":null},
  {"name":"extends dans un for","template":"{% for x in y %}\n{% extends 'a' %}{% endfor %}","klipper":{"line":2,"message":"cannot use extend from a non top-level scope"},"kalico":{"line":2,"message":"cannot use extend from a non top-level scope"}},
  {"name":"extends puis sortie ignorée","template":"{% extends 'a' %}{ x|inconnu }","klipper":null,"kalico":null},
  {"name":"extends puis set contrôlé","template":"{% extends 'a' %}{% set y = x|inconnu %}","klipper":{"line":1,"message":"no filter named 'inconnu'"},"kalico":{"line":1,"message":"No filter named 'inconnu'."}},
  {"name":"double extends","template":"{% extends 'a' %}{% extends 'b' %}{% set y = x|inconnu %}","klipper":null,"kalico":null},
  {"name":"bloc défini deux fois","template":"{% block a %}{% endblock %}\n{% block a %}{% endblock %}","klipper":{"line":2,"message":"block 'a' defined twice"},"kalico":{"line":2,"message":"block 'a' defined twice"}},
  {"name":"endblock d'un autre nom","template":"{% block a %}{% endblock b %}","klipper":{"line":1,"message":"expected token 'end of statement block', got 'b'"},"kalico":{"line":1,"message":"expected token 'end of statement block', got 'b'"}},
  {"name":"nom de bloc avec tiret","template":"{% block a-b %}{% endblock %}","klipper":{"line":1,"message":"Block names in Jinja have to be valid Python identifiers and may not contain hyphens, use an underscore instead."},"kalico":{"line":1,"message":"Block names in Jinja have to be valid Python identifiers and may not contain hyphens, use an underscore instead."}},
  {"name":"bloc required","template":"{% block a required %}x{% endblock %}","klipper":{"line":1,"message":"expected token 'end of statement block', got 'required'"},"kalico":{"line":1,"message":"Required blocks can only contain comments or whitespace"}},
  {"name":"bloc required vide","template":"{% block a required %}  {# c #}{% endblock %}","klipper":{"line":1,"message":"expected token 'end of statement block', got 'required'"},"kalico":null},
  {"name":"caller sans défaut","template":"{% macro m(caller) %}{ caller() }{% endmacro %}","klipper":{"line":1,"message":"When defining macros or call blocks the special \"caller\" argument must be omitted or be given a default."},"kalico":{"line":1,"message":"When defining macros or call blocks the special \"caller\" argument must be omitted or be given a default."}},
  {"name":"caller avec défaut","template":"{% macro m(caller=none) %}{ caller() }{% endmacro %}","klipper":null,"kalico":null},
  {"name":"caller non utilisé","template":"{% macro m(caller) %}x{% endmacro %}","klipper":null,"kalico":null},
  {"name":"argument sans défaut après défaut","template":"{% macro m(a=1, b) %}{% endmacro %}","klipper":{"line":1,"message":"non-default argument follows default argument"},"kalico":{"line":1,"message":"non-default argument follows default argument"}},
  {"name":"call sans appel","template":"{% call m %}{% endcall %}","klipper":{"line":1,"message":"expected call"},"kalico":{"line":1,"message":"expected call"}},
  {"name":"boucle nommée loop","template":"{% for loop in x %}{% endfor %}","klipper":{"line":1,"message":"Can't assign to special loop variable in for-loop target"},"kalico":{"line":1,"message":"Can't assign to special loop variable in for-loop target"}},
  {"name":"set loop dans une boucle","template":"{% for x in y %}\n{% set loop = 1 %}{% endfor %}","klipper":{"line":2,"message":"Can't assign to special loop variable in for-loop target"},"kalico":{"line":2,"message":"Can't assign to special loop variable in for-loop target"}},
  {"name":"affectation à une constante","template":"{% set true = 1 %}","klipper":{"line":1,"message":"can't assign to 'const'"},"kalico":{"line":1,"message":"can't assign to 'const'"}},
  {"name":"affectation à un attribut entre parenthèses","template":"{% for (a.b) in z %}{% endfor %}","klipper":{"line":1,"message":"can't assign to 'getattr'"},"kalico":{"line":1,"message":"can't assign to 'getattr'"}},
  {"name":"macro nommée true","template":"{% macro true() %}{% endmacro %}","klipper":{"line":1,"message":"can't assign to 'name'"},"kalico":{"line":1,"message":"can't assign to 'name'"}},
  {"name":"tuple en cible de for","template":"{% for a, b in c %}{% endfor %}{% for a, in c %}{% endfor %}","klipper":{"line":1,"message":"expected token 'in', got 'c'"},"kalico":{"line":1,"message":"expected token 'in', got 'c'"}},
  {"name":"import d'un nom privé","template":"{% from 'x' import _a %}","klipper":{"line":1,"message":"names starting with an underline can not be imported"},"kalico":{"line":1,"message":"names starting with an underline can not be imported"}},
  {"name":"import avec virgule finale","template":"{% from 'x' import a, %}","klipper":{"line":1,"message":"expected token 'name', got 'end of statement block'"},"kalico":{"line":1,"message":"expected token 'name', got 'end of statement block'"}},
  {"name":"import sans nom","template":"{% from 'x' import %}","klipper":{"line":1,"message":"expected token 'name', got 'end of statement block'"},"kalico":{"line":1,"message":"expected token 'name', got 'end of statement block'"}},
  {"name":"print vide","template":"{% print %}","klipper":null,"kalico":null},
  {"name":"set sans valeur","template":"{% set a = %}","klipper":{"line":1,"message":"Expected an expression, got 'end of statement block'"},"kalico":{"line":1,"message":"Expected an expression, got 'end of statement block'"}},
  {"name":"namespace simple","template":"{% set ns = namespace(a=0) %}{% set ns.a = 1 %}","klipper":null,"kalico":null},
  {"name":"namespace dans un tuple","template":"{% set ns = namespace(b=0) %}{% set a, ns.b = 1, 2 %}","klipper":{"line":1,"message":"expected token 'end of statement block', got '.'"},"kalico":null},
  {"name":"listes et tranches","template":"{% set x = [1, 2,] %}{ {'a': 1,} }{ a[1:2:3] }{ a[::] }{ a[1, 2] }","klipper":null,"kalico":null},
  {"name":"do","template":"{% set l = [] %}{% do l.append(1) %}","klipper":{"line":1,"message":"Encountered unknown tag 'do'."},"kalico":null},
  {"name":"break dans une boucle","template":"{% for x in y %}{% if x %}{% break %}{% endif %}{% continue %}{% endfor %}","klipper":{"line":1,"message":"Encountered unknown tag 'break'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."},"kalico":null},
  {"name":"break hors boucle","template":"G28\n{% break %}","klipper":{"line":2,"message":"Encountered unknown tag 'break'."},"kalico":{"python":"SyntaxError"}},
  {"name":"continue dans le else d'un for","template":"{% for x in y %}{% else %}{% continue %}{% endfor %}","klipper":{"line":1,"message":"Encountered unknown tag 'continue'. Jinja was looking for the following tags: 'endfor'. The innermost block that needs to be closed is 'for'."},"kalico":{"python":"SyntaxError"}},
  {"name":"break dans le else d'un for imbriqué","template":"{% for x in y %}{% for z in x %}{% else %}{% break %}{% endfor %}{% endfor %}","klipper":{"line":1,"message":"Encountered unknown tag 'break'. Jinja was looking for the following tags: 'endfor'. The innermost block that needs to be closed is 'for'."},"kalico":null},
  {"name":"break dans le else d'un for récursif","template":"{% for x in y %}{% for z in x recursive %}{% else %}{% break %}{% endfor %}{% endfor %}","klipper":{"line":1,"message":"Encountered unknown tag 'break'. Jinja was looking for the following tags: 'endfor'. The innermost block that needs to be closed is 'for'."},"kalico":{"python":"SyntaxError"}},
  {"name":"break dans une macro dans une boucle","template":"{% for x in y %}{% macro m() %}{% break %}{% endmacro %}{% endfor %}","klipper":{"line":1,"message":"Encountered unknown tag 'break'. Jinja was looking for the following tags: 'endmacro'. The innermost block that needs to be closed is 'macro'."},"kalico":{"python":"SyntaxError"}},
  {"name":"break dans un set bloc dans une boucle","template":"{% for x in y %}{% set s %}{% break %}{% endset %}{% endfor %}","klipper":{"line":1,"message":"Encountered unknown tag 'break'. Jinja was looking for the following tags: 'endset'. The innermost block that needs to be closed is 'set'."},"kalico":null},
  {"name":"hexadécimal en 3.x","template":"{ 0x1F + 0b101 + 0o17 }","klipper":{"line":1,"message":"expected token 'end of print statement', got 'x1F'"},"kalico":null},
  {"name":"zéros en tête","template":"{ 007 }","klipper":null,"kalico":{"line":1,"message":"expected token 'end of print statement', got 'integer'"}},
  {"name":"fin de bloc +%}","template":"{% if x +%}G28{% endif +%}","klipper":{"line":1,"message":"unexpected 'end of statement block'"},"kalico":null},
  {"name":"échappement \\x tronqué","template":"{ '\\x4' }","klipper":{"line":1,"message":"truncated \\xXX escape"},"kalico":{"line":1,"message":"truncated \\xXX escape"}},
  {"name":"échappement \\u tronqué","template":"{ \"\\u12\" }","klipper":{"line":1,"message":"truncated \\uXXXX escape"},"kalico":{"line":1,"message":"truncated \\uXXXX escape"}},
  {"name":"échappement \\U hors Unicode","template":"{ '\\U00110000' }","klipper":{"line":1,"message":"illegal Unicode character"},"kalico":{"line":1,"message":"illegal Unicode character"}},
  {"name":"échappement \\N mal formé","template":"{ '\\N{abc' }","klipper":{"line":1,"message":"malformed \\N character escape"},"kalico":{"line":1,"message":"malformed \\N character escape"}},
  {"name":"échappements valides","template":"{ 'é\\x41\\u00e9\\n\\q\\é\\101' }","klipper":null,"kalico":null},
  {"name":"identifiant invalide","template":"{ x² }","klipper":{"line":1,"message":"Invalid character in identifier"},"kalico":{"line":1,"message":"Invalid character in identifier"}},
  {"name":"tabulation verticale","template":"{ x\u000by }","klipper":{"line":2,"message":"expected token 'end of print statement', got 'y'"},"kalico":{"line":1,"message":"expected token 'end of print statement', got 'y'"}},
  {"name":"commentaire ouvert en toute fin","template":"G28 {#","klipper":null,"kalico":null},
  {"name":"raw ouvert en toute fin","template":"G28 {% raw %}","klipper":null,"kalico":null},
  {"name":"raw avec contrôle des blancs","template":"{% raw -%}  x  {%- endraw %}","klipper":null,"kalico":null},
  {"name":"blocs imbriqués non fermés","template":"{% if a %}\nG28\n{% for x in y %}\nG1","klipper":{"line":3,"message":"Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'."},"kalico":{"line":3,"message":"Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'."}},
  {"name":"erreur d'imbrication","template":"{% for x in y %}{% if x %}{% endfor %}","klipper":{"line":1,"message":"Encountered unknown tag 'endfor'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."},"kalico":{"line":1,"message":"Encountered unknown tag 'endfor'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."}},
  {"name":"fin après une accolade et un saut de ligne","template":"M117 {\n","klipper":{"line":1,"message":"unexpected 'end of template'"},"kalico":{"line":1,"message":"unexpected 'end of template'"}},
  {"name":"if non fermé avec lignes vides finales","template":"{% if x %}\n\n","klipper":{"line":1,"message":"Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."},"kalico":{"line":1,"message":"Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'."}},
  {"name":"fins de ligne Windows","template":"{% if x %}\r\n{ y|inconnu }\r\n{% endif %}","klipper":{"line":2,"message":"no filter named 'inconnu'"},"kalico":null},
  {"name":"argument nommé mot-clé Python valide","template":"{ f(if=1) }","klipper":null,"kalico":null},
  {"name":"filtre à point","template":"{ x|a.b }","klipper":{"line":1,"message":"no filter named 'a.b'"},"kalico":{"line":1,"message":"No filter named 'a.b'."}},
];
