// SPDX-License-Identifier: GPL-3.0-only
import { describe, expect, it } from "vitest";
import { loadSchema } from "../config/firmwares";
import { readConfig } from "../config/ini";
import { indexMacros } from "../macros/semantics";
import { checkGcode, type GcodeConfigContext, readGcodeFacts } from "./klipper-checks";

// Le paquet autonome n'a ni types Node ni DOM (pas de TextEncoder) ; le G-code est en ASCII.
const ascii = (text: string) => Uint8Array.from(text, (c) => c.charCodeAt(0));
const gcode = (...lines: string[]) => ascii(`${lines.join("\n")}\n`);

const BASE = ["[printer]", "kinematics: none", "max_velocity: 1", "max_accel: 1"];

async function contextOf(lines: readonly string[]): Promise<GcodeConfigContext> {
  const { sections } = readConfig({
    files: new Map([["printer.cfg", [...BASE, ...lines].join("\n")]]),
    main: "printer.cfg",
  });
  return {
    sections: new Set(sections.map((s) => s.name)),
    macros: indexMacros(sections, await loadSchema("klipper"), "klipper"),
  };
}

const codes = (checks: ReturnType<typeof checkGcode>) =>
  checks.map((c) => `${c.severity} ${c.code} ${c.line ?? "-"}`);

describe("faits du G-code (EP-04.10)", () => {
  it("arcs, objets, première extrusion, commandes étendues, chauffes du début", () => {
    const facts = readGcodeFacts(
      gcode(
        "; generated by PrusaSlicer",
        "EXCLUDE_OBJECT_DEFINE NAME=cube CENTER=100,100",
        "M190 S60",
        "M109 S210",
        "PRINT_START BED=60 EXTRUDER=210 ; macro",
        "G1 E5 F300",
        "G1 X10 Y10 E2.5",
        "EXCLUDE_OBJECT_START NAME=cube",
        "G2 X20 Y20 I5 J5 E1",
        "PRINT_START BED=70",
        "M104 S0",
      ),
    );
    expect(facts.arcs).toEqual({ count: 1, firstLine: 9 });
    expect(facts.excludeObject).toEqual({ defines: 1, firstDefineLine: 2, others: 1 });
    expect(facts.firstExtrusionLine).toBe(7);
    expect(facts.calls).toEqual([
      { command: "PRINT_START", line: 5, raw: "PRINT_START BED=60 EXTRUDER=210" },
    ]);
    expect(facts.startTemperatures.map((t) => [t.command, t.target])).toEqual([
      ["M190", 60],
      ["M109", 210],
    ]);
  });
});

describe("règles Klipper du G-code, sans configuration", () => {
  it("arcs signalés à vérifier ; maillage adaptatif sans objet ; M109 avant M190", () => {
    const checks = checkGcode(
      readGcodeFacts(
        gcode(
          "M109 S210",
          "M190 S60",
          "BED_MESH_CALIBRATE ADAPTIVE=1",
          "G1 X1 Y1 E1",
          "G3 X2 Y2 R5 E1",
        ),
      ),
    );
    expect(codes(checks)).toEqual([
      "info gcode.heat-order 1",
      "warning gcode.adaptive-no-objects 3",
      "info gcode.arcs-check 5",
    ]);
  });

  it("extrusion sans aucune chauffe attendue ; une macro avant peut chauffer (pas d'alerte)", () => {
    expect(codes(checkGcode(readGcodeFacts(gcode("M104 S210", "G1 X1 Y1 E1"))))).toEqual([
      "warning gcode.extrude-before-heat 2",
    ]);
    expect(checkGcode(readGcodeFacts(gcode("START_PRINT", "G1 X1 Y1 E1")))).toEqual([]);
  });

  it("objets définis après le palpage adaptatif : maillage complet", () => {
    const checks = checkGcode(
      readGcodeFacts(
        gcode(
          "M190 S60",
          "M109 S210",
          "BED_MESH_CALIBRATE ADAPTIVE=1",
          "EXCLUDE_OBJECT_DEFINE NAME=a",
        ),
      ),
    );
    expect(checks).toEqual([
      {
        code: "gcode.adaptive-before-objects",
        severity: "warning",
        line: 3,
        params: { defineLine: 4 },
      },
    ]);
  });
});

describe("règles Klipper du G-code, avec la configuration", () => {
  const MACRO = [
    "[gcode_macro PRINT_START]",
    "gcode:",
    "  {% set bed = params.BED_TEMP|float %}",
    "  {% set tool = params.EXTRUDER_TEMP|default(200)|float %}",
    "  M190 S{bed}",
    "  M109 S{tool}",
    "  BED_MESH_CALIBRATE ADAPTIVE=1",
  ];

  it("arcs sans [gcode_arcs] : erreur ; objets sans [exclude_object] ; commande inconnue", async () => {
    const context = await contextOf(MACRO);
    const checks = checkGcode(
      readGcodeFacts(
        gcode(
          "EXCLUDE_OBJECT_DEFINE NAME=a",
          "PRINT_START BED_TEMP=60",
          "G1 X1 Y1 E1",
          "G2 X5 Y5 I1 J1 E1",
          "PRINT_FINISH",
        ),
      ),
      context,
    );
    expect(codes(checks)).toEqual([
      "warning gcode.exclude-object-unsupported 1",
      "error gcode.arcs-unsupported 4",
      "warning gcode.unknown-command 5",
    ]);
  });

  it("paramètres : transmis mais jamais lus, attendus mais absents (nom différent)", async () => {
    const context = await contextOf([...MACRO, "[exclude_object]"]);
    const checks = checkGcode(
      readGcodeFacts(
        gcode(
          "EXCLUDE_OBJECT_DEFINE NAME=a",
          "PRINT_START BED=60 EXTRUDER_TEMP=210",
          "G1 X1 Y1 E1",
        ),
      ),
      context,
    );
    expect(checks).toEqual([
      {
        code: "gcode.macro-param-unused",
        severity: "warning",
        line: 2,
        params: { macro: "PRINT_START", param: "BED", read: "BED_TEMP, EXTRUDER_TEMP" },
      },
      {
        code: "gcode.macro-param-missing",
        severity: "warning",
        line: 2,
        params: { macro: "PRINT_START", param: "BED_TEMP" },
      },
    ]);
  });

  it("maillage adaptatif dans la macro, objets définis après son appel ; la macro chauffe", async () => {
    const context = await contextOf([...MACRO, "[exclude_object]", "[gcode_arcs]"]);
    const checks = checkGcode(
      readGcodeFacts(
        gcode(
          "PRINT_START BED_TEMP=60",
          "EXCLUDE_OBJECT_DEFINE NAME=a",
          "G1 X1 Y1 E1",
          "G2 X1 Y1 R2 E1",
        ),
      ),
      context,
    );
    expect(codes(checks)).toEqual(["warning gcode.adaptive-before-objects 1"]);
  });

  it("macro qui ne chauffe pas la buse avant l'extrusion : alerte", async () => {
    const context = await contextOf(["[gcode_macro START]", "gcode:", "  G28"]);
    expect(codes(checkGcode(readGcodeFacts(gcode("START", "G1 X1 Y1 E1")), context))).toEqual([
      "warning gcode.extrude-before-heat 2",
    ]);
  });
});

describe("règles Klipper du G-code : cas limites", () => {
  it("lignes indentées, minuscules, fins de ligne Windows, octets non ASCII, consigne en R", () => {
    const facts = readGcodeFacts(
      ascii(
        [
          "\t; commentaire",
          "  m190 r60 ; attend",
          "\tm109 S0",
          "  print_start nom=pièce\r",
          "g1 x1 y1 e0.5\r",
          "G4 P100",
          "",
        ].join("\n"),
      ),
    );
    expect(facts.startTemperatures).toEqual([
      { command: "M190", line: 2, target: 60 },
      { command: "M109", line: 3, target: 0 },
    ]);
    expect(facts.calls).toEqual([
      { command: "PRINT_START", line: 4, raw: "print_start nom=pi?ce" },
    ]);
    expect(facts.firstExtrusionLine).toBe(5);
  });

  it("attente par TEMPERATURE_WAIT de l'extrudeur dans le G-code : pas d'alerte", async () => {
    const context = await contextOf([]);
    const facts = readGcodeFacts(
      gcode("M104 S210", "TEMPERATURE_WAIT SENSOR=extruder MINIMUM=200", "G1 X1 Y1 E1"),
    );
    expect(checkGcode(facts, context)).toEqual([]);
  });

  it("macro dynamique : paramètres non jugés ; macros qui s'appellent en boucle sans fin", async () => {
    const context = await contextOf([
      "[gcode_macro START]",
      "gcode:",
      "  {% for key in params %}RESPOND MSG={key}{% endfor %}",
      "  BOUCLE",
      "[gcode_macro BOUCLE]",
      "gcode:",
      "  START",
      "  M109 S{params.T|default(200)}",
    ]);
    const facts = readGcodeFacts(gcode("START COULEUR=rouge", "G1 X1 Y1 E1"));
    expect(checkGcode(facts, context)).toEqual([]);
  });

  it("modules inconnus du firmware : commande inconnue seulement « à vérifier »", async () => {
    const context = await contextOf([
      "[module_maison]",
      "option: 1",
      "[gcode_macro START]",
      "gcode:",
      "  M109 S200",
    ]);
    const checks = checkGcode(readGcodeFacts(gcode("START", "MAISON_GO", "G1 X1 Y1 E1")), context);
    expect(codes(checks)).toEqual(["info gcode.unknown-command 2"]);
  });

  it("ADAPTIVE calculé ou nul : pas de maillage adaptatif certain ; objets bien placés : rien", async () => {
    expect(
      checkGcode(readGcodeFacts(gcode("M190 S60", "M109 S200", "BED_MESH_CALIBRATE ADAPTIVE={a}"))),
    ).toEqual([]);
    expect(
      checkGcode(
        readGcodeFacts(
          gcode(
            "EXCLUDE_OBJECT_DEFINE NAME=a",
            "M190 S60",
            "M109 S200",
            "BED_MESH_CALIBRATE ADAPTIVE=1",
          ),
        ),
      ),
    ).toEqual([]);
    const context = await contextOf(["[exclude_object]"]);
    expect(
      checkGcode(
        readGcodeFacts(
          gcode("EXCLUDE_OBJECT_DEFINE NAME=a", "M109 S200", "EXCLUDE_OBJECT_START NAME=a"),
        ),
        context,
      ),
    ).toEqual([]);
  });
});
