// SPDX-License-Identifier: GPL-3.0-only
import { describe, expect, it } from "vitest";
import { parseDuration, readGcodeMetadata } from "./metadata";

// Le paquet autonome n'a pas TextEncoder ; les extraits sont en ASCII.
const ascii = (text: string) => Uint8Array.from(text, (c) => c.charCodeAt(0));
const file = (...lines: string[]) => ascii(`${lines.join("\n")}\n`);
// 1 × 1 pixel PNG, encodé en base64.
const PIXEL =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";

describe("readGcodeMetadata (EP-04.03)", () => {
  it("PrusaSlicer : en-tête, vignette, bloc de fin ; jamais le mode silencieux", () => {
    const meta = readGcodeMetadata(
      file(
        "; generated by PrusaSlicer 2.9.0 on 2026-10-06 at 08:00:00 UTC",
        ";",
        "; thumbnail begin 16x16 92",
        `; ${PIXEL.slice(0, 50)}`,
        `; ${PIXEL.slice(50)}`,
        "; thumbnail end",
        "G1 X10 E1",
        "; filament used [mm] = 676.57, 0.00",
        "; filament used [g] = 1.76, 0.00",
        "; total filament used [g] = 1.76",
        "; total filament used for wipe tower [g] = 0.00",
        "; estimated printing time (normal mode) = 1h 17m 27s",
        "; estimated printing time (silent mode) = 1h 20m 1s",
        "; estimated first layer printing time (normal mode) = 1m 57s",
        "; filament_diameter = 1.75,1.75",
        "; layer_height = 0.2",
        "; nozzle_diameter = 0.6,0.4",
      ),
    );
    expect(meta).toEqual({
      slicer: "PrusaSlicer",
      version: "2.9.0",
      estimatedSeconds: 4647,
      filamentMm: 676.57,
      filamentGrams: 1.76,
      filamentDiameter: 1.75,
      layerHeight: 0.2,
      nozzleDiameter: 0.6,
      thumbnails: [{ width: 16, height: 16, format: "png", base64: PIXEL }],
    });
  });

  it("Bambu Studio : temps total, longueur et masse par filament additionnées", () => {
    const meta = readGcodeMetadata(
      file(
        "; HEADER_BLOCK_START",
        "; BambuStudio 01.10.01.50",
        "; model printing time: 1h 2m 3s; total estimated time: 1h 9m 3s",
        "; total layer number: 150",
        "; total filament length [mm] : 4000.00,500.50",
        "; total filament weight [g] : 12.00,1.50",
        "; HEADER_BLOCK_END",
        "; filament_diameter = 1.75,1.75",
      ),
    );
    expect(meta).toMatchObject({
      slicer: "BambuStudio",
      version: "01.10.01.50",
      estimatedSeconds: 4143,
      filamentMm: 4500.5,
      filamentGrams: 13.5,
      filamentDiameter: 1.75,
    });
  });

  it("OrcaSlicer : « generated by », temps du mode normal", () => {
    const meta = readGcodeMetadata(
      file(
        "; generated by OrcaSlicer 2.2.0 on 2026-10-06 at 10:00:00",
        "; estimated printing time (normal mode) = 2d 1h",
        "; layer_height = 0.16",
      ),
    );
    expect(meta).toMatchObject({
      slicer: "OrcaSlicer",
      version: "2.2.0",
      estimatedSeconds: 176_400,
      layerHeight: 0.16,
    });
  });

  it("Cura : temps en secondes, filament en mètres, couche et buse", () => {
    const meta = readGcodeMetadata(
      file(
        ";FLAVOR:Marlin",
        ";TIME:3725",
        ";Filament used: 1.25m, 0.5m",
        ";Layer height: 0.12",
        ";NOZZLE_DIAMETER:0.4",
        ";Generated with Cura_SteamEngine 5.8.1",
      ),
    );
    expect(meta).toMatchObject({
      slicer: "Cura",
      version: "5.8.1",
      estimatedSeconds: 3725,
      filamentMm: 1750,
      layerHeight: 0.12,
      nozzleDiameter: 0.4,
    });
    // Variante volumétrique : pas une longueur.
    expect(readGcodeMetadata(file(";Filament used: 1234mm3")).filamentMm).toBeUndefined();
    // Saveur Griffin.
    expect(
      readGcodeMetadata(file(";PRINT.TIME:60", ";EXTRUDER_TRAIN.0.NOZZLE.DIAMETER:0.8")),
    ).toMatchObject({ estimatedSeconds: 60, nozzleDiameter: 0.8 });
  });

  it("vignettes : JPEG gardé, QOI et base64 invalide ignorés, triées par taille", () => {
    const meta = readGcodeMetadata(
      file(
        "; thumbnail_QOI begin 32x32 8",
        "; cW9pZg==",
        "; thumbnail_QOI end",
        "; thumbnail_JPG begin 300x300 8",
        "; /9j/4AAQ",
        "; thumbnail_JPG end",
        "; thumbnail begin 48x48 8",
        "; pas du base64 !",
        "; thumbnail end",
        "; thumbnail begin 16x16 92",
        `; ${PIXEL}`,
        "; thumbnail end",
      ),
    );
    expect(meta.thumbnails.map((t) => [t.width, t.format])).toEqual([
      [16, "png"],
      [300, "jpg"],
    ]);
  });

  it("valeurs illisibles : la métadonnée reste vide, sans exception", () => {
    const meta = readGcodeMetadata(
      file(
        "; estimated printing time (normal mode) = n/a",
        "; model printing time: ?; total estimated time: ?",
        "; filament used [mm] = abc",
        ";Filament used: m",
        "; total filament used [g] = ?",
        "; filament used [g] = -",
        "; filament_diameter = x",
        "; layer_height = 0",
        "; nozzle_diameter = ,",
      ),
    );
    expect(meta).toEqual({ thumbnails: [] });
  });

  it("G-code sans commentaires de slicer : rien, sans exception", () => {
    expect(readGcodeMetadata(file("G1 X10 E1"))).toEqual({ thumbnails: [] });
    expect(readGcodeMetadata(new Uint8Array())).toEqual({ thumbnails: [] });
  });

  it("gros fichier : fin lue séparément du début", () => {
    const body = "G1 X1 E0.01\n".repeat(80_000);
    const meta = readGcodeMetadata(
      ascii(`; generated by SuperSlicer 2.5.59 on x\n${body}; layer_height = 0.3\n`),
    );
    expect(meta).toMatchObject({ slicer: "SuperSlicer", layerHeight: 0.3 });
  });

  it.each([
    ["17m 27s", 1047],
    ["1d 2h 3m 4s", 93_784],
    ["45s", 45],
    ["n/a", undefined],
  ])("parseDuration(%s) = %s", (text, seconds) => {
    expect(parseDuration(text)).toBe(seconds);
  });
});
