// SPDX-License-Identifier: GPL-3.0-only

/**
 * Métadonnées des slicers dans les commentaires du G-code (EP-04.03) : slicer et version, temps
 * estimé, filament (longueur, masse), diamètre du filament, hauteur de couche, buse, vignettes.
 * Formats relevés dans le code source de chaque slicer (octobre 2026) :
 * - PrusaSlicer, SuperSlicer, OrcaSlicer : `; generated by <Nom> <version> on …`,
 *   `; estimated printing time (normal mode) = 1h 2m 3s`, `; filament used [mm] = a, b`,
 *   `; filament used [g] = a, b`, `; total filament used [g] = x`, et le bloc de réglages
 *   `; filament_diameter = 1.75,1.75`, `; layer_height = 0.2`, `; nozzle_diameter = 0.4,0.4`,
 *   `; filament_type = PLA;PETG`, `; filament_max_volumetric_speed = 15,15` ;
 * - Bambu Studio (et OrcaSlicer) : `; BambuStudio <version>`, `; model printing time: …; total
 *   estimated time: 1h 2m`, `; total filament length [mm] : a,b`, `; total filament weight [g] : a,b` ;
 * - Cura : `;Generated with Cura_SteamEngine <version>`, `;TIME:<secondes>` (ou `;PRINT.TIME:`),
 *   `;Filament used: 1.2m, 0.5m`, `;Layer height: 0.2`, `;NOZZLE_DIAMETER:0.4` (ou
 *   `;EXTRUDER_TRAIN.0.NOZZLE.DIAMETER:0.4`) ;
 * - vignettes (tous) : `; thumbnail begin <l>x<h> <taille>`, base64, `; thumbnail end` ;
 *   `thumbnail_JPG` pour le JPEG ; `thumbnail_QOI` ignoré (aucun navigateur ne l'affiche).
 * Seuls le début et la fin du fichier sont lus (les métadonnées y sont toutes).
 */

export const GCODE_SLICERS = [
  "PrusaSlicer",
  "SuperSlicer",
  "OrcaSlicer",
  "BambuStudio",
  "Cura",
] as const;
export type GcodeSlicer = (typeof GCODE_SLICERS)[number];

export interface GcodeThumbnail {
  readonly width: number;
  readonly height: number;
  readonly format: "png" | "jpg";
  /** Image encodée en base64. */
  readonly base64: string;
}

export interface GcodeMetadata {
  readonly slicer?: GcodeSlicer | undefined;
  readonly version?: string | undefined;
  readonly estimatedSeconds?: number | undefined;
  readonly filamentMm?: number | undefined;
  readonly filamentGrams?: number | undefined;
  readonly filamentDiameter?: number | undefined;
  readonly layerHeight?: number | undefined;
  readonly nozzleDiameter?: number | undefined;
  /** Matériau déclaré (premier extrudeur), en majuscules : « PLA », « PETG »… (EP-04.11). */
  readonly filamentType?: string | undefined;
  /** Débit volumétrique maximal déclaré pour le filament (mm³/s), si non nul. */
  readonly maxVolumetricSpeed?: number | undefined;
  /** Vignettes, de la plus petite à la plus grande. */
  readonly thumbnails: readonly GcodeThumbnail[];
}

/** Octets lus au début et à la fin du fichier. */
const WINDOW = 512 * 1024;
/** Taille maximale d'une vignette décodée (base64), au-delà ignorée. */
const MAX_THUMBNAIL_BASE64 = 2_000_000;

function ascii(bytes: Uint8Array, from: number, to: number): string {
  let text = "";
  const chunk = 8192;
  for (let k = from; k < to; k += chunk) {
    text += String.fromCharCode(...bytes.subarray(k, Math.min(to, k + chunk)));
  }
  return text;
}

/** « 1d 2h 3m 4s », « 17m 27s » → secondes ; undefined si illisible. */
export function parseDuration(text: string): number | undefined {
  let total = 0;
  let found = false;
  for (const [, amount, unit] of text.matchAll(/(\d+(?:\.\d+)?)\s*([dhms])/g)) {
    const factor = { d: 86_400, h: 3_600, m: 60, s: 1 }[unit as "d" | "h" | "m" | "s"];
    total += Number(amount) * factor;
    found = true;
  }
  return found ? Math.round(total) : undefined;
}

/** Liste « 1.2, 0.00,3 » → somme ; undefined si aucun nombre. */
const sum = (text: string): number | undefined => {
  const values = text.split(",").map((v) => Number.parseFloat(v));
  const numbers = values.filter(Number.isFinite);
  return numbers.length > 0 ? numbers.reduce((a, b) => a + b, 0) : undefined;
};
/** Première valeur d'une liste par extrudeur. */
const first = (text: string): number | undefined => {
  const value = Number.parseFloat(text.split(",")[0] ?? "");
  return Number.isFinite(value) && value > 0 ? value : undefined;
};

export function readGcodeMetadata(bytes: Uint8Array): GcodeMetadata {
  const head = ascii(bytes, 0, Math.min(bytes.length, WINDOW));
  const tail =
    bytes.length > WINDOW
      ? ascii(bytes, Math.max(WINDOW, bytes.length - WINDOW), bytes.length)
      : "";
  const meta: {
    -readonly [K in keyof GcodeMetadata]: GcodeMetadata[K];
  } & { thumbnails: GcodeThumbnail[] } = { thumbnails: [] };
  let gramsTotal: number | undefined;

  let thumbnail:
    | { width: number; height: number; format: "png" | "jpg" | "skip"; parts: string[] }
    | undefined;
  for (const text of [head, tail]) {
    for (const raw of text.split("\n")) {
      const line = raw.trim();
      if (!line.startsWith(";")) continue;
      const body = line.replace(/^;\s?/, "");

      // Vignettes.
      const begin = /^thumbnail(?:_(PNG|JPG|QOI))? begin (\d+)x(\d+)/i.exec(body);
      if (begin) {
        const kind = (begin[1] ?? "PNG").toUpperCase();
        thumbnail = {
          width: Number(begin[2]),
          height: Number(begin[3]),
          format: kind === "JPG" ? "jpg" : kind === "PNG" ? "png" : "skip",
          parts: [],
        };
        continue;
      }
      if (thumbnail) {
        if (/^thumbnail(?:_\w+)? end/i.test(body)) {
          const base64 = thumbnail.parts.join("");
          if (
            thumbnail.format !== "skip" &&
            base64.length > 0 &&
            base64.length <= MAX_THUMBNAIL_BASE64 &&
            /^[A-Za-z0-9+/]+=*$/.test(base64)
          ) {
            meta.thumbnails.push({
              width: thumbnail.width,
              height: thumbnail.height,
              format: thumbnail.format,
              base64,
            });
          }
          thumbnail = undefined;
        } else {
          thumbnail.parts.push(body.trim());
        }
        continue;
      }

      // Slicer et version.
      let match = /^generated by (PrusaSlicer|SuperSlicer|OrcaSlicer|BambuStudio) ([^\s]+)/i.exec(
        body,
      );
      if (match && !meta.slicer) {
        meta.slicer = GCODE_SLICERS.find((s) => s.toLowerCase() === match?.[1]?.toLowerCase());
        meta.version = match[2];
        continue;
      }
      match = /^(BambuStudio|OrcaSlicer) (\d[^\s]*)$/i.exec(body);
      if (match && !meta.slicer) {
        meta.slicer = GCODE_SLICERS.find((s) => s.toLowerCase() === match?.[1]?.toLowerCase());
        meta.version = match[2];
        continue;
      }
      match = /^Generated with Cura_SteamEngine ([^\s]+)/i.exec(body);
      if (match && !meta.slicer) {
        meta.slicer = "Cura";
        meta.version = match[1];
        continue;
      }

      // Temps estimé : le mode normal ou le total, jamais le mode silencieux ni la 1re couche.
      match = /^estimated printing time \(normal mode\) = (.+)$/.exec(body);
      if (match) {
        meta.estimatedSeconds = parseDuration(match[1] ?? "") ?? meta.estimatedSeconds;
        continue;
      }
      match = /total estimated time: (.+)$/.exec(body);
      if (match) {
        meta.estimatedSeconds = parseDuration(match[1] ?? "") ?? meta.estimatedSeconds;
        continue;
      }
      match = /^(?:PRINT\.)?TIME:(\d+)$/.exec(body);
      if (match) {
        meta.estimatedSeconds = Number(match[1]);
        continue;
      }

      // Filament.
      match = /^(?:total )?filament (?:used|length) \[mm\] ?[=:] (.+)$/.exec(body);
      if (match) {
        meta.filamentMm = sum(match[1] ?? "") ?? meta.filamentMm;
        continue;
      }
      match = /^Filament used: (.+)$/.exec(body);
      if (match && /m\s*(,|$)/.test(match[1] ?? "") && !/mm3/.test(match[1] ?? "")) {
        const meters = sum((match[1] ?? "").replace(/m/g, ""));
        if (meters !== undefined) meta.filamentMm = meters * 1000;
        continue;
      }
      match = /^total filament (?:used|weight) \[g\] ?[=:] (.+)$/.exec(body);
      if (match) {
        gramsTotal = sum(match[1] ?? "");
        continue;
      }
      match = /^filament used \[g\] = (.+)$/.exec(body);
      if (match) {
        meta.filamentGrams = sum(match[1] ?? "") ?? meta.filamentGrams;
        continue;
      }

      // Réglages.
      match = /^filament_diameter = (.+)$/.exec(body);
      if (match) {
        meta.filamentDiameter = first(match[1] ?? "") ?? meta.filamentDiameter;
        continue;
      }
      match = /^(?:layer_height = |Layer height: )(.+)$/.exec(body);
      if (match) {
        meta.layerHeight = first(match[1] ?? "") ?? meta.layerHeight;
        continue;
      }
      match =
        /^(?:nozzle_diameter = |NOZZLE_DIAMETER:|EXTRUDER_TRAIN\.0\.NOZZLE\.DIAMETER:)(.+)$/.exec(
          body,
        );
      if (match) {
        meta.nozzleDiameter = first(match[1] ?? "") ?? meta.nozzleDiameter;
        continue;
      }
      // Matériau et débit maximal (PrusaSlicer, SuperSlicer, OrcaSlicer, Bambu Studio) :
      // `; filament_type = PLA;PETG`, `; filament_max_volumetric_speed = 15,15` (0 : sans limite).
      match = /^filament_type = (.+)$/.exec(body);
      if (match) {
        const type = (match[1] ?? "").split(/[;,]/)[0]?.trim().toUpperCase();
        if (type) meta.filamentType = type;
        continue;
      }
      match = /^filament_max_volumetric_speed = (.+)$/.exec(body);
      if (match) {
        const speed = first(match[1] ?? "");
        if (speed !== undefined && speed > 0) meta.maxVolumetricSpeed = speed;
      }
    }
    thumbnail = undefined;
  }
  if (gramsTotal !== undefined) meta.filamentGrams = gramsTotal;
  meta.thumbnails.sort((a, b) => a.width * a.height - b.width * b.height);
  return meta;
}
